name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme dcjwu
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          REPOSITORY: dcjwu/dcjwu
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          LANG_COUNT: 5
